# Generated by Django 3.0.8 on 2020-07-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viwes',
            field=models.IntegerField(default=0),
        ),
    ]
